site_name: FamiStudio Documentation
nav:
- Welcome: index.md   
- User Guide:
  - "Installation": install.md
  - "Basics": basics.md
  - "Editing Notes": pianoroll.md
  - "Editing Patterns": sequencer.md
  - "Editing Instruments & Arpeggios": instruments.md
  - "Editing Songs & Project": song.md
  - "Editing DPCM Samples": dpcm.md
  - "Importing Songs": import.md
  - "Exporting Songs": export.md
  - "Using Expansion Audio": expansion.md
  - "Cleaning-up your Project": cleanup.md
  - "Configuring FamiStudio": config.md
  - "Command-line Processing": cmdline.md
  - "NES/Famicom Sound Engine": soundengine.md
  - "Troubleshooting": troubleshooting.md
  - "Acknowledgements": thanks.md
- Change Log:
  - "All Version History": changelog.md
  - "FamiStudio 4.2.0 Highlights": releases/420.md
  - "FamiStudio 4.3.0 Highlights": releases/430.md
  - "FamiStudio 4.4.0 Highlights": releases/440.md
extra_css:
    - css/extra.css    
theme: 
  name: slate
  color_mode: dark
plugins:
  - search
  - meta-descriptions
